apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-new
spec:
  capacity:
    storage: 2Gi  # Increased storage to avoid conflicts
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql-new"  # Changed path to avoid conflicts
