name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs the pipeline when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full repository is fetched
          submodules: true  # Fetch submodules if any

      - name: Debug Directory and Fix Working Directory
        run: |
          pwd
          ls -lah
          cd connecting-mysql || cd $GITHUB_WORKSPACE
          ls -lah

      - name: Build JAR file with Correct Directory
        run: |
          cd connecting-mysql || cd $GITHUB_WORKSPACE
          mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t viha06/connecting-mysql-spring-app:latest .
          docker push viha06/connecting-mysql-spring-app:latest

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Restart Deployment
        run: kubectl rollout restart deployment/spring-app
